- name: Step2
  hosts: all
  gather_facts: no
  remote_user: sshadmin
  become: true
  become_user: root
  vars_files:
    - vars/main.yml

  tasks:

  - name: copy scripts to /etc/zabbix folder
    copy:
      src: files/script
      dest: /etc/zabbix/
      backup: yes
      owner: root
      group: root
      mode: 0755

