---

create_users:
  - user: zabbix
    comment: 'zabbix service account'
    pass: "z@bb1xhijkill"
    state: present
    sudo: true

Hostname: worker1

ServerList: 10.17.14.103,10.17.14.104
ActiveServerList: 10.17.14.103,10.17.14.104

FileList:
- { file: zabbix_sender, dest: /usr/local/sbin/zabbix_sender }
- { file: zabbix_agent, dest: /usr/local/sbin/zabbix_agent }
- { file: zabbix_agentd, dest: /usr/local/sbin/zabbix_agentd }
- { file: zabbix_get, dest: /usr/local/sbin/zabbix_get }
- { file: zabagstrt, dest: /usr/local/bin/zabagentstart }
- { file: zabagstop, dest: /usr/local/bin/zabagentstop }
